### ISSUE TITLE
Adding a Date and a Duration

### ISSUE THREAD

**Issue by romaintailhurat** [VTL-Community/VTL-Community#38]
The VTL spec doesn't allow for this kind of semantic:

`Date + Duration → Date`

For example, we would like to add 3 days to the 3rd of october (`2023-10-03`) in order to have the 6th of october (`2023-10-06`).

It's obviously not a simple case of adding numbers because we need to handle variable months durations (including leap years).

**Comment by linardian** [comment]
I think that the new dateadd() operator will "close the gap". If so, please consider this issue closed.

**Comment by romaintailhurat** [comment]
Let's close it.
