### ISSUE TITLE
Clarify behaviour of Median operator

### ISSUE THREAD

**Issue by javihern98** [VTL-Community/VTL-Community#46]
Looking at the examples of the Reference Manual, there seems to be some behaviour to clarify in the median operator:

![image](https://github.com/VTL-Community/VTL-Community/assets/73304358/85d6e721-7b7c-45e4-a7df-175aef763744)

The example (and the SQL function based on it), seems to be taking the mean value of the two middle numbers (Id_1=2012).

As this [article](https://subhralina.medium.com/5-ways-to-calculate-median-in-sql-cffba38aa945) suggests:

Median: The middle number; found by ordering all data points and picking out the one in the middle (or if there are two middle numbers, taking the mean of those two numbers).

Other approach: taking the first value of the two intermediate numbers, this is how it is implemented in PySpark

@linardian @FranckCo @jmsimonma-md  please comment which approach is correct and why, and if we should clarify this better...

**Comment by linardian** [comment]
Good afternoon.
​In my opinioni the results are correct in both cases. If the number of items is odd, the middle one is taken, if it is even, the mean of the two central ones is calculated. Do you have any other opinion about this rule? If so let us discuss it.
Best regards

Angelo

**Comment by antonio-olleros** [comment]
Hi Angelo, I think that the issue is that the manual doesn't say anything, and it should. I agree that the preferred solution should be the SQL one, but it should be explicitly documented in the manual

**Comment by linardian** [comment]
Ok, even though the definition of the median is relatively “standard” and the described algorithm is widely used.
I will amend the manual ready for the 2.1.1 release.
Thank you so much for pointing it out.
Best

Angelo

**Comment by javihern98** [comment]
Edited comments for clarity, awaiting for @linardian confirmation that the manual has been updated to close this issue

**Comment by linardian** [comment]
This is the extract of the "live" 2.1.1 release:

Behaviour
The operator returns the median value of the input values, found by ordering all values and picking out the one in the middle (or if there are two middle numbers, taking the mean of those two numbers).
For other details, see Aggregate and Analytic invocations.

**Comment by javihern98** [comment]
I agree on the clarification. @linardian Shall we close this issue?

**Comment by linardian** [comment]
Yes, please

**Comment by antonio-olleros** [comment]
I would suggest that we don't close until the action is taken, otherwise we may lose the issues, would you agree?
