### ISSUE TITLE
Behaviour of Join operators with a single dataset

### ISSUE THREAD

**Issue by javihern98** [VTL-Community/VTL-Community#47]
The join operators syntax definition specifically states that "at least one dataset must be present"

![image](https://github.com/user-attachments/assets/bf793e6e-b576-4033-8c4b-9702e4ff67a1)

However, the behaviour of all join operators implies more than one dataset (operands):

![image](https://github.com/user-attachments/assets/8e11a635-ff8e-4d16-bed0-185212524229)

We propose to enforce the join operators to have at least two operands, or specifically clarify the behaviour of a join with a single dataset.

Please check, @linardian

**Comment by linardian** [comment]
Yes, I would change the following sentence:

Input parameters
joinOperator		the Join operator to be applied
ds1, …, dsN		the Data Set operands (at least **one** --> **two** must be present)
alias1, …, aliasN	..... 

Changed applied to the "live" 2.1.1 version:

Input parameters
joinOperator		the Join operator to be applied
ds1, …, dsN		the Data Set operands (at least two must be present)
alias1, …, aliasN	....

**Comment by javihern98** [comment]
Yes, also in the syntax part:

 { , ds { as alias } }* -->  { , ds { as alias } }+ (to indicate that more than one must be present, to make a total minimum of two datasets, in accordance to the Syntax guidelines and to be reproduced in the ANTLR Grammar files.

**Comment by antonio-olleros** [comment]
Hi all, I agree, but what makes me unease is that looks like done on purpose, anyone has a memory of any reason why it could be defined this way?

**Comment by javihern98** [comment]
This test must be changed accordingly, adding DS_2 as operand:

![image](https://github.com/user-attachments/assets/43a3b8f7-6357-4a3f-8dd4-2aa73d468b1f)

**Comment by linardian** [comment]
The intent was to simplify the inner join, non forcing to specify twice the same operand. 
That said, we can decide to adopt one of the three options:

1. leave everything as it is, adding an annotation saying that the possibility to specify only one operand is restricted to the inner join operator
2. force also for inner join the presence of two (in this case twice the same one) operators
3. split the definition of the join operator in two (or more parts) for the different types of join

My slight preference goes to the first one, but I am glad to receive more opinions.

**Comment by javihern98** [comment]
@linardian As this is a very edge use case, I would like to request the enforcement of the presence of two operators (i.e. option number 2) for consistency. SQL also enforces the use of two operands, even if it is the same.

**Comment by linardian** [comment]
These are the changes applied to the join operator (in bold):

joinOperator ( ds1 { as alias1 }**, ds2 { as alias2 }**  { , dsN { as aliasN } }* 
{ using usingComp { , usingComp }*} 
{ filter filterCondition } 
{ apply applyExpr
| calc calcClause 
   			| aggr aggrClause { groupingClause } } 
{ keep comp {, comp }* | drop comp {, comp }* }
{ rename compFrom to compTo { , compFrom to compTo }* }
       	)

ds1, …, dsN		the Data Set operands (at least **two** must be present)

a note has been added:

In the previous versions for inner_join only one Data Set operand had to be specified; to be more consistent and similarly to SQL syntax, at least to operands are required.

and the example 6 has been changed:

Example 6:		
DS_r  := inner_join ( DS_1 as d1**, DS_1 as d2,**
calc Me_2 := Me_2 || “_NEW”
filter Id_2 =”B”
keep Me_1, Me_2)		
where || is the string concatenation, 		results in:


Let me know if some more updates are required.

**Comment by javihern98** [comment]
No more updates are required, closing this issue.
