### ISSUE TITLE
Type casting in ternary expressions

### ISSUE THREAD

**Issue by romaintailhurat** [VTL-Community/VTL-Community#6]
At Insee we use VTL in our data collection systems for controls and computations.

It is common to write such conditionnal expressions:

`if (isnull(QUANTITY)) then 0 else (cast(PRICE, integer) / cast(QUANTITY, integer))`

This previous line will not compile, the problem here being that we **must** use a decimal as the first value of the ternary expression (`0.0` below):

`if (isnull(QUANTITY)) then 0.0 else (cast(PRICE, integer) / cast(QUANTITY, integer))`

It would be less cumbersome if we could express our computation the first way, having similar semantics as in other languages, for example Python:

```python
0 if x is None else x / y
```

**Comment by vpinna80** [comment]
There is a discussion of implicit casting in VTL reference manual starting at 1961 and integer-to-number case is at 1981.

Corrected the answer because the division result is indeed a number in every case.
