### ISSUE TITLE
If Then without else 

### ISSUE THREAD

**Issue by ddecrulle** [VTL-Community/VTL-Community#9]
Hi,

First of all, according to my test (using VTL throughout [Trevas JS](https://github.com/InseeFr/Trevas-JS)) and the [documentation](https://sdmx.org/wp-content/uploads/VTL-2.0-Reference-Manual-20180712-final.pdf) (page 25) an operator **if** is always followed by **then** (which is logical) and **else**. 

If I'm right, what do you find to let the posibility to use if ... then **without** else ? 

Thanks,
Dylan.

**Comment by NicoLaval** [comment]
Hello,

What would be your use case?

**Comment by ddecrulle** [comment]
Mi case is very simple, 

I do question label customisation. This customisation can depend on metadata or on the answer to a previous question. In this case it is sometimes necessary to display something when the condition is true, but not to display anything when it is not.

**Comment by NicoLaval** [comment]
Hi,

You can manage by adding your default value into the else clause.

```
a := if booleanExpr then "my text" else ""
```

Else definition ensure consistency of the returned type.
